db_data:
  image: busybox
  volumes:
      - /var/lib/mysql
  command: sh


db:
  image: mysql
  volumes_from:
      - db_data
  ports:
         - "3306:3306"
  environment:
         MYSQL_ROOT_PASSWORD: password
  privileged: true

web:
  build: .

  command: /bin/bash -c "export PYENV='develop' && nginx && uwsgi --ini /code/mysite_uwsgi.ini && tail -f /dev/null"

  # これだとdocker-compose start の度にパッケージインストールとかすることになるので問題。
  # command: /bin/bash -c "sudo pip install --no-cache-dir -r requirements.txt && yes | mkdir /var/log/uwsgi && yes | apt-get install gettext && nginx && uwsgi --ini /code/mysite_uwsgi.ini && tail -f /dev/null"

  volumes:
         # - .:/code
         - /Users/user/develop/universear:/code
  ports:
         - "8000:8000"
         - "8001:8001"
         - "8443:8443"
  links:
         - db
  privileged: true
